### ISSUE TITLE
Project is big (38MB) - takes ages to Checkout

### ISSUE THREAD

**Issue by dav009** [lightning-viz/lightning-scala#10]
This project takes ages to git checkout(still downloading 25MB..).
I wonder if there are old jar files which were added and then removed in the working tree.

It would be good to have a cleanup, as this seems to see just a wrapper around an API

**Comment by freeman-lab** [comment]
Thanks for flagging this! We very recently added experimental support for IScala notebooks and inadvertently included a large jar file. This has been fixed and the repo cleaned, so now checking out should be trivially fast. If you can confirm, I'll close this.

**Comment by dav009** [comment]
:+1:  wow super fast checkout
