### ISSUE TITLE
Do not know how to convert JString(...) into int

### ISSUE THREAD

**Issue by fmarchand** [lightning-viz/lightning-scala#17]
I'm following the README and I have this error message when I tried to run `sbt assembly` : 
    `Do not know how to convert JString(...) into int`

I would like to try lightning using Zeppelin. But I'm stuck with this message. Did I miss something ?

**Comment by IAmMalte** [comment]
Same here

**Comment by mathisonian** [comment]
just merged #16 which should fix this. thanks @amaiberg!
